name: Build on PR for dev branch

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally if not available

      - name: Install dependencies with pnpm
        run: pnpm install  # Use pnpm to install dependencies

      - name: Build project
        run: pnpm run build  # Run build command with pnpm
