# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: food_wagon

on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      #- run: sudo chown -R ubuntu:ubuntu /home/ubuntu/cicd_footnote_client/_work/
      #- run: sudo chown -R ubuntu:ubuntu /home/ubuntu/cicd_footnote_client/_work/footnote-client
      #- run: sudo chown -R ubuntu:ubuntu /home/ubuntu/cicd_ui_client/_work/indiajets-client/indiajets-client/node_modules
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: cd /home/ubuntu/ui/cicd_jupiter/_work/jupiter_conversion_new/jupiter_conversion_new
      - run: pnpm i
      - run: pnpm build
      - run: sudo chmod -R 777 /home/ubuntu/ui/cicd_jupiter/_work/jupiter_conversion_new/jupiter_conversion_new
        #- run:
        #   sudo chmod -R 777 /home/ubuntu/cicd_ui_client/_work/indiajets-client/indiajets-client/build/
        shell: bash
